# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Payload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Payload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Payload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Payload
    def Observations(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Observation import Observation
            obj = Observation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Payload
    def ObservationsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Payload
    def ObservationsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    PayloadStart(builder)

def PayloadAddObservations(builder, observations):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(observations), 0)

def AddObservations(builder, observations):
    PayloadAddObservations(builder, observations)

def PayloadStartObservationsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartObservationsVector(builder, numElems):
    return PayloadStartObservationsVector(builder, numElems)

def PayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return PayloadEnd(builder)
